from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .integrity import sha256_file


def lockdown_state(path: Path = Path("/sys/kernel/security/lockdown")) -> str:
    if not path.exists():
        return "UNAVAILABLE"
    text = path.read_text(encoding="utf-8", errors="replace").strip()
    if "[confidentiality]" in text:
        return "CONFIDENTIALITY"
    if "[integrity]" in text:
        return "INTEGRITY"
    return "NONE"


def install_hardening_assets(target_root: Path, source_root: Path | None = None) -> list[Path]:
    target_root = Path(target_root)
    source_root = source_root or Path(__file__).resolve().parent.parent / "hardening"
    apparmor_src = source_root / "apparmor.d" / "chromaplex-generated"
    lockdown_src = source_root / "60-chromaplex-lockdown.cfg"
    if not apparmor_src.exists() or not lockdown_src.exists():
        raise RuntimeError("Hardening assets are missing from the package")
    parser = shutil.which("apparmor_parser")
    if parser:
        check = subprocess.run([parser, "-Q", "-T", str(apparmor_src)], capture_output=True, text=True, check=False)
        if check.returncode != 0:
            raise RuntimeError("AppArmor profile validation failed: " + (check.stderr or check.stdout))
    outputs = []
    apparmor_dst = target_root / "etc/apparmor.d/chromaplex-generated"
    grub_dst = target_root / "etc/default/grub.d/60-chromaplex-lockdown.cfg"
    apparmor_dst.parent.mkdir(parents=True, exist_ok=True)
    grub_dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(apparmor_src, apparmor_dst); outputs.append(apparmor_dst)
    shutil.copy2(lockdown_src, grub_dst); outputs.append(grub_dst)
    return outputs



def generate_apparmor_profile(
    binary_path: Path,
    workspace_path: Path,
    capability_manifest,
    *,
    profile_name: str = "chromaplex-rpi-app",
) -> str:
    """Generate a conservative Raspberry Pi AppArmor deployment profile.

    This is deliberately target-side policy: the Coding Agent does not pretend
    that a hash alone grants OS trust. The generated profile mirrors the
    approved capability manifest and can be installed/enforced on the Pi.
    """
    from .capabilities import CapabilityManifest
    from .targets import get_target

    caps = capability_manifest
    if not isinstance(caps, CapabilityManifest):
        raise TypeError("capability_manifest must be a CapabilityManifest")
    caps.validate()
    profile = get_target(caps.target)
    if not profile.is_raspberry_pi:
        raise ValueError("AppArmor deployment profile generation is only valid for Raspberry Pi Linux targets")

    binary = str(Path(binary_path))
    workspace = str(Path(workspace_path))
    if not binary.startswith("/") or not workspace.startswith("/"):
        raise ValueError("Raspberry Pi deployment paths must be absolute")
    if not re.fullmatch(r"[A-Za-z0-9_.-]{1,80}", profile_name):
        raise ValueError("invalid AppArmor profile name")

    lines = [
        "# Generated by Chromaplex Coding Agent v0.4 Secure Compile Gate",
        "# Review before installation on the Raspberry Pi target.",
        f"profile {profile_name} {binary} flags=(attach_disconnected,mediate_deleted) {{",
        "  #include <abstractions/base>",
        "  /usr/lib/** r,",
        "  /lib/** r,",
        "  /lib64/** r,",
        "  /etc/ld.so.cache r,",
        "  /etc/ssl/certs/** r,",
        "  /dev/null rw,",
        "  /dev/urandom r,",
        f"  {binary} rix,",
    ]
    if caps.workspace_write:
        lines.append(f"  {workspace}/** rwk,")
    elif caps.workspace_read:
        lines.append(f"  {workspace}/** r,")
    if caps.network:
        lines.append("  network,")
    if caps.process_spawn:
        lines.extend(["  /usr/bin/** ix,", "  /bin/** ix,"])
    # No /home/**, /root/**, /etc/** write, raw block devices, ptrace or mount
    # rules are emitted. AppArmor therefore denies them by default.
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_apparmor_profile(
    output_path: Path,
    binary_path: Path,
    workspace_path: Path,
    capability_manifest,
    *,
    profile_name: str = "chromaplex-rpi-app",
    validate: bool = True,
) -> Path:
    text = generate_apparmor_profile(binary_path, workspace_path, capability_manifest, profile_name=profile_name)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    parser = shutil.which("apparmor_parser") if validate else None
    if parser:
        check = subprocess.run([parser, "-Q", "-T", str(output)], capture_output=True, text=True, check=False)
        if check.returncode != 0:
            output.unlink(missing_ok=True)
            raise RuntimeError("Generated AppArmor profile validation failed: " + (check.stderr or check.stdout))
    return output

def format_verity(data_image: Path, hash_image: Path, *, veritysetup: str | None = None, timeout: int = 300) -> dict:
    tool = veritysetup or shutil.which("veritysetup")
    if not tool:
        raise RuntimeError("veritysetup is unavailable (install cryptsetup-bin)")
    data_image = Path(data_image).resolve(); hash_image = Path(hash_image).resolve()
    if not data_image.is_file():
        raise RuntimeError(f"data image does not exist: {data_image}")
    hash_image.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run([tool, "format", str(data_image), str(hash_image), "--hash=sha256"], capture_output=True, text=True, timeout=timeout, check=False)
    if proc.returncode != 0:
        raise RuntimeError("veritysetup format failed: " + (proc.stderr or proc.stdout))
    text = (proc.stdout or "") + "\n" + (proc.stderr or "")
    root = re.search(r"Root hash:\s*([0-9a-fA-F]+)", text)
    salt = re.search(r"Salt:\s*([0-9a-fA-F]+)", text)
    if not root:
        raise RuntimeError("veritysetup succeeded but no Root hash was reported")
    manifest = {
        "schema": "chromaplex-dm-verity-v1",
        "created_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "algorithm": "sha256",
        "data_image": data_image.name,
        "data_image_sha256": sha256_file(data_image),
        "hash_image": hash_image.name,
        "hash_image_sha256": sha256_file(hash_image),
        "root_hash": root.group(1).lower(),
        "salt": salt.group(1).lower() if salt else "",
        "read_only": True,
    }
    manifest_path = hash_image.with_name(hash_image.name + ".verity.json")
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description="Chromaplex ChromaLinux hardening helper")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check-lockdown")
    install = sub.add_parser("install-assets"); install.add_argument("target_root", type=Path)
    verity = sub.add_parser("format-verity"); verity.add_argument("data_image", type=Path); verity.add_argument("hash_image", type=Path)
    aa = sub.add_parser("generate-rpi-apparmor")
    aa.add_argument("binary_path", type=Path); aa.add_argument("workspace_path", type=Path); aa.add_argument("capability_manifest", type=Path); aa.add_argument("output_path", type=Path)
    aa.add_argument("--profile-name", default="chromaplex-rpi-app")
    args = parser.parse_args()
    if args.cmd == "check-lockdown":
        state = lockdown_state(); print(state); return 0 if state in {"INTEGRITY", "CONFIDENTIALITY"} else 2
    if args.cmd == "install-assets":
        for p in install_hardening_assets(args.target_root): print(p)
        return 0
    if args.cmd == "generate-rpi-apparmor":
        from .capabilities import CapabilityManifest
        caps = CapabilityManifest.from_json(args.capability_manifest.read_text(encoding="utf-8"))
        out = write_apparmor_profile(args.output_path, args.binary_path, args.workspace_path, caps, profile_name=args.profile_name)
        print(out); return 0
    manifest = format_verity(args.data_image, args.hash_image); print(json.dumps(manifest, indent=2)); return 0

if __name__ == "__main__":
    raise SystemExit(main())
